name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONTAINER: rust-rv32emc
  CONTAINER_ARCHIVE: rust-rv32emc.tar.gz

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build . --file Containerfile --tag $CONTAINER --target minimal
        docker save $CONTAINER -o $CONTAINER_ARCHIVE
    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: $CONTAINER_ARCHIVE
        path: $CONTAINER_ARCHIVE
        if-no-files-found: error

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'https://github.com/hegza/riscv/'
          ref: 'feat/rve'
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: $CONTAINER_ARCHIVE
      - name: Expand image
        run: docker load -i $CONTAINER_ARCHIVE
      - name: Run test.sh
        run: |
          docker cp test.sh
          docker cp $CONTAINER:/root/test.sh
          docker exec -w=/root/ -it $CONTAINER /root/test.sh
