name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONTAINER_ARCHIVE: rust-rv32emc.tar.gz

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        TAG=$(date +%s)
        docker build . --file Containerfile --tag rust-rv32emc:$TAG
        docker save rust-rv32emc:$TAG -o $CONTAINER_ARCHIVE
    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: $CONTAINER_ARCHIVE
        path: $CONTAINER_ARCHIVE
        if-no-files-found: error
